### ISSUE TITLE
Problem with YAML anchors

### ISSUE THREAD

**Issue by EntropyWorks** [coolaj86/yamltojson.com#11]
So it the out put of this YAML when run on http://yamltojson.com/ is different than what is on http://yaml-online-parser.appspot.com/

```yaml
---
shared_settings:
  foo_var: &foo
    variable: TRUE
  bar_var: &bar
    variable: FLASE

testing: 
 example: 
  1: 
   <<: *foo
  2:
   <<: *foo
   variable: "Just me is different"
  3: 
   <<: *bar
  4: 
   <<: *bar
   variable: "REALLY TRUE"
```

The output looks wrong to me.

```json
{
  "shared_settings": {
    "foo_var": {
      "variable": "Just me is different"
    },
    "bar_var": {
      "variable": "REALLY TRUE"
    }
  },
  "testing": {
    "example": {
      "1": {
        "variable": "Just me is different"
      },
      "2": {
        "variable": "Just me is different"
      },
      "3": {
        "variable": "REALLY TRUE"
      },
      "4": {
        "variable": "REALLY TRUE"
      }
    }
  }
}
```
It should look like the following.

```json
{
  "testing": {
    "example": {
      "1": {
        "variable": true
      }, 
      "2": {
        "variable": "Just me is different"
      }, 
      "3": {
        "variable": "FLASE"
      }, 
      "4": {
        "variable": "REALLY TRUE"
      }
    }
  }, 
  "shared_settings": {
    "foo_var": {
      "variable": true
    }, 
    "bar_var": {
      "variable": "FLASE"
    }
  }
}
```
